apiVersion: v1
kind: Pod
metadata:
  name: fake-vn
spec:
  containers:
  - name: fake-vn
    image: ibaboutest/fake-vn:latest
    imagePullPolicy: Always
    args:
    - /virtual-kubelet
    - --nodename
    - test-node-01
    - --provider-config
    - /vkubelet-cfg.json
    - --startup-timeout
    - 20s
    - --klog.v
    - "2"
    - --klog.logtostderr
    env:
    - name: KUBELET_PORT
      value: "10250"
    - name: VKUBELET_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    ports:
    - name: metrics
      containerPort: 10255
  serviceAccountName: fake-virtual-kubelet
